/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutSection: typeof import('./src/components/Sections/AboutSection/AboutSection.vue')['default']
    AnimatedTooltip: typeof import('./src/components/UI/Tooltip/AnimatedTooltip.vue')['default']
    Button: typeof import('./src/components/UI/Button/Button.vue')['default']
    CardSpotlight: typeof import('./src/components/UI/СardSpotlight/CardSpotlight.vue')['default']
    CirclePreloader: typeof import('./src/components/UI/Preloader/CirclePreloader.vue')['default']
    FlipWords: typeof import('./src/components/UI/FlipWords/FlipWords.vue')['default']
    GeometricLink: typeof import('./src/components/UI/Decoration/GeometricLink.vue')['default']
    GlassmorphismCard: typeof import('./src/components/UI/GlassmorphismCard/GlassmorphismCard.vue')['default']
    GlowBorder: typeof import('./src/components/UI/GlowBorder/GlowBorder.vue')['default']
    Header: typeof import('./src/components/App/Header/Header.vue')['default']
    HeroSection: typeof import('./src/components/Sections/HeroSection/HeroSection.vue')['default']
    IconCloud: typeof import('./src/components/UI/IconCloud/IconCloud.vue')['default']
    Link: typeof import('./src/components/UI/Link/Link.vue')['default']
    LiquidBackground: typeof import('./src/components/UI/LiquidBackground/LiquidBackground.vue')['default']
    NavigationMenu: typeof import('./src/components/UI/NavigationMenu/NavigationMenu.vue')['default']
    NavigationMenuContent: typeof import('./src/components/UI/NavigationMenu/NavigationMenuContent.vue')['default']
    NavigationMenuIndicator: typeof import('./src/components/UI/NavigationMenu/NavigationMenuIndicator.vue')['default']
    NavigationMenuItem: typeof import('./src/components/UI/NavigationMenu/NavigationMenuItem.vue')['default']
    NavigationMenuLink: typeof import('./src/components/UI/NavigationMenu/NavigationMenuLink.vue')['default']
    NavigationMenuList: typeof import('./src/components/UI/NavigationMenu/NavigationMenuList.vue')['default']
    NavigationMenuTrigger: typeof import('./src/components/UI/NavigationMenu/NavigationMenuTrigger.vue')['default']
    NavigationMenuViewport: typeof import('./src/components/UI/NavigationMenu/NavigationMenuViewport.vue')['default']
    Preloader: typeof import('./src/components/UI/Preloader/Preloader.vue')['default']
    Profile: typeof import('./src/components/Widget/Profile/Profile.vue')['default']
    ProfileInfo: typeof import('./src/components/Sections/AboutSection/ProfileInfo.vue')['default']
    RainbowButton: typeof import('./src/components/UI/RainbowButton/RainbowButton.vue')['default']
    SacredGeometry: typeof import('./src/components/UI/Decoration/SacredGeometry.vue')['default']
    StatCard: typeof import('./src/components/Sections/AboutSection/StatCard.vue')['default']
    StatsGrid: typeof import('./src/components/Sections/AboutSection/StatsGrid.vue')['default']
    StripsPreloader: typeof import('./src/components/UI/Preloader/StripsPreloader.vue')['default']
    TechCategory: typeof import('./src/components/Sections/AboutSection/TechCategory.vue')['default']
    TechStack: typeof import('./src/components/Sections/AboutSection/TechStack.vue')['default']
  }
}
